### ISSUE TITLE
Different values for daily usage

### ISSUE THREAD

**Issue by sefininio** [GuyKh/bezeq-energy-custom-component#26]
## System Information

version | core-2024.11.3
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 4.15.0-194-generic
arch | x86_64
timezone | Asia/Jerusalem
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4988
Installed Version | 2.0.1
Stage | running
Available Repositories | 1475
Downloaded Repositories | 23

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 33

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | August 17, 2025 at 3:00 AM
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
cloud_ice_servers_enabled | true
remote_server | eu-central-1-14.ui.nabu.casa
certificate_status | ready
instance_id | a4de4ad502b54059a52696a01502c0d2
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 10
views | 42
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 23, 2024 at 4:25 AM
-- | --
current_recorder_run | November 26, 2024 at 11:39 AM
estimated_db_size | 1839.55 MiB
database_engine | mysql
database_version | 11.6.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/GuyKh/bezeq-energy-custom-component/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The bezeq extension reports the same value as the app for daily consumption, but the app has another value that is probably from a different api call and seems to be more accurate, so maybe it should be used instead (see attachments - the extension reports 647.920 which rounds to 648 - the value in the graph. But the app has another value 709 for the daily consumption )

![SmartSelect_20241126_193314_Home Assistant](https://github.com/user-attachments/assets/052b059b-0c57-4ce9-bc3c-18977ee71d26)
![IMG-20241126-WA0002](https://github.com/user-attachments/assets/fdd85bc7-1762-4e19-b1f3-b04d16bf4e03)

### Reproduction steps

1. Check the value in HA
2. Check the value in the bezeq app
3.
...

### Debug logs

```text
N/a
```

**Comment by GuyKh** [comment]
Indeed it comes from different calls:
The monthly usage calculation is take from a call to get Monthly usage (`https://my-api.bezeq.co.il/v72.3/api/ElectricityTab/GetElectReportByYear`)
While what you see on the tab header is taken from the header of the electricity tab.

It's a good question when it comes to the actual source of truth...
`https://my-api.bezeq.co.il/v72.3/api/ElectricityTab/GetElectricityTab`
->
```
  {
            "BillingServiceId": 70,
            "BillingServiceCode": "ElectricityMonthlyUsed",
            "BillingServiceDescription": "צריכת החשמל שלי",
            "CardType": "ElectricityMonthlyUsed",
            "ServiceType": "ElectricityMonthlyUsed",
            "CardDetails": "{\"UsedAmount\":123,\"FromDate\":\"\\/Date(1730412000000)\\/\"}",
            "Makat": null,
            "Quantity": null,
            "SN": null,
            "Mac": null,
            "Link": null,
            "EnterLink": null,
            "ShowMeshMgt": false,
            "Id": 2,
            "Title": "צריכה חודשית מצטברת",
            "SubTitle": null,
            "Picture": null,
            "Order": 2
        },
```

Now, although this number is indeed higher, but it's not even decimal, I'm really not sure it should be used for this calculation...

**Comment by sefininio** [comment]
Well, up to you 😁
I'd go with the higher value - the monthly will catch up with it, I guess they are stupid and make the calculations twice or the monthly is calculated once a day and the bigger value is updated on a higher frequency.
Why is decimal important?

**Comment by GuyKh** [comment]
I think that decimal point gives an indication of accuracy.

**Comment by GuyKh** [comment]
Also - this looks very unreliable, I think
Today I see that the monthly bar is about 250, while the top value says above 500....

**Comment by sefininio** [comment]
Yes, I see that now, that value is 3 times the normal one. That sucks.

**Comment by GuyKh** [comment]
Yep. Closing this for now
